# THIS FILE IS NOT USED BY VAGRANT. It's used by Jenkins to build the production and
# staging sites.
#
# If you want to modify the Jekyll configuration used by everyone's Vagrant machine, edit:
#   deploy/roles/dev/files/_config.yml
# To make those changes permanent, copy them here.
name: Rackspace Developer Portal
url: http://developer.rackspace.com

markdown: kramdown
kramdown:
 input: GFM
highlighter: pygments
paginate: 10
relative_permalinks: true
permalink: posts/:title
paginate_path: /blog/page:num
recent_posts: 5
excerpt_separator: "<!-- more -->"

# jekyll-assets plugin configuration.
assets:
  js_compressor: ~
  css_compressor: ~
  cache: true
