---
- name: Log the firewall
  ufw: logging=on

- name: Allow SSH access on ServiceNet
  ufw: rule=allow if=eth1 port=22 proto=tcp direction=in

- name: Allow SSH access from specific hosts
  ufw: rule=allow src={{ item }} port=22 proto=tcp
  with_items: ip_accesses

- name: Allow access to 80 on ServiceNet
  ufw: rule=allow if=eth1 port=80 proto=tcp direction=in

- name: Drop everything else
  ufw: policy=reject state=enabled
