---
- name: Stop any old site_source watchers
  command: pkill -f 'SCREEN.*site_source_watcher'
  sudo: yes
  ignore_errors: yes

- name: Start site_source watcher
  shell: export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && screen -dmS site_source_watcher jekyll build --watch --source . --destination /var/www/html/developer.rackspace.com/ chdir=/vagrant_data/site_source
  sudo: yes
  sudo_user: publisher
