---
- name: Disable password authentication for SSH
  copy: src=etc/ssh/sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
  - restart ssh server

- name: Create user for pushing static site
  user: name=publisher comment="Site Publisher" state=present
        groups=www-data

- name: Add SSH public key to authorized_keys for publisher user
  authorized_key: user=publisher key="{{ lookup('file', 'id_rsa.pub') }}"
                  state=present

- name: Copy motd file
  copy: src=etc/motd dest=/etc/motd owner=root group=root mode=0644

- name: Make publisher user owner of docroot directory
  file: path={{ docroot }} owner=publisher recurse=yes state=directory

- name: Prequisites for apt_repository tasks
  apt: name=python-apt state=installed

- name: Node.js PPA
  apt_repository: repo='ppa:chris-lea/node.js' state=present update_cache=yes

- name: Recent node.js
  apt: name=nodejs state=installed
  sudo: yes

- name: Log the firewall
  ufw: logging=on

- name: Allow SSH access on ServiceNet
  ufw: rule=allow if=eth1 port=22 proto=tcp direction=in

- name: Allow SSH access from specific hosts
  ufw: rule=allow src={{ item }} port=22 proto=tcp
  with_items: ip_accesses

- name: Allow access to 8080 on ServiceNet
  ufw: rule=allow if=eth1 port=8080 proto=tcp direction=in

- name: Drop everything else
  ufw: policy=reject state=enabled
