---
- name: Setup a web server running Nginx
  hosts: webservers
  sudo: yes
  roles:
    - role: bennojoy.nginx
      nginx_http_params:
        sendfile: "on"
        access_log: "/var/log/nginx/access.log"
      nginx_sites:
        - server:
            file_name: developer.rackspace.com
            listen: 80
            server_name: "{{ server_name }}"
            root: "/var/www/html/developer.rackspace.com"
