---
# This playbook is invoked by Jenkins to build the site and rsync it out
# to each webserver.

- name: Build the site locally first.
  hosts: local
  connection: local
  tasks:

  - name: Run the build script to generate the site.
    command: ../build_site.sh

- name: Deploy content to the chosen webserver group.
  hosts: "{{ group }}"
  remote_user: publisher
  vars_files:
  - paths.yml
  roles:
  - role: content
    srcroot: ..
