---
# Copy this file to "secrets.yml" and fill in these values with the credentials
# for a Rackspace cloud account to test the node.js backend.

# If you're running in dev mode with Vagrant, run `vagrant provision` after you
# modify this file for changes to take effect.

rackspace_username:
rackspace_apikey:

# Mailgun credentials
mailgun_apikey:
mailgun_domain:

# Email that should receive sponsorship emails
sponsorship_notification_email:
