---
# Paths that should be common across playbooks.

# Destination directory for the static HTML.
docroot: /var/www/html/developer.rackspace.com

# Directory for the sponsorship-form backend.
backendroot: /var/webapp/drc-backend

# Rackspace region in which the CDN and sponsorship form upload containers should be created.
common_region: IAD

# Zones from which monitoring checks will be performed.
monitoring_zones:
- mzdfw
- mziad
- mzord

# Destination container for production static assets.
production_container: drc-static-prod

# Destination container for staging static assets.
staging_container: drc-static-staging

# TTL value for CDN containers.
cdn_ttl: 31536000
