---
- name: Install fileschanged for the watcher service
  apt: name={{ item }} update_cache=yes
  with_items:
  - fileschanged
  sudo: yes

- name: Install the watcher's init script
  template: src=watcher.conf.j2 dest=/etc/init/watcher.conf
  sudo: yes

- name: Ensure that the watcher has started
  service: name=watcher state=started

- name: Fix the permissions of the site destination folder
  file: path=/vagrant_data/_site state=directory owner=vagrant group=vagrant recurse=yes

- name: Kick off an initial build
  shell: ./build_site.sh chdir=/vagrant_data
  sudo: yes
  sudo_user: vagrant
