---
- name: Create Jenkins users, jobs and other DRG-specific configuration
  sudo: yes
  copy:
    src: var/lib/jenkins/
    dest: /var/lib/jenkins/
  notify:
    - 'Restart Jenkins'

- name: Copy motd file
  copy: src=deploy/roles/jenkins_masters/files/etc/motd
        dest=/etc/motd
        owner=root group=root mode=0644

- name: Dynamically set Jenkins IP address in Jenkins config file
  sudo: yes
  template:
    src: var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
  notify:
    - 'Restart Jenkins'

- name: Create directory for 'build_prod_site' job
  sudo: yes
  file:
    path: "/var/lib/jenkins/jobs/build_prod_site"
    state: directory
    owner: jenkins
    group: jenkins
  notify:
    - 'Restart Jenkins'

- name: Dynamically create 'build_prod_site' job config with production web server IP list
  sudo: yes
  template:
    src: "var/lib/jenkins/jobs/build_prod_site/config.xml.j2"
    dest: "/var/lib/jenkins/jobs/build_prod_site/config.xml"
  notify:
    - 'Restart Jenkins'

- name: Create directory for 'build_staging_site' job
  sudo: yes
  file:
    path: "/var/lib/jenkins/jobs/build_staging_site"
    state: directory
    owner: jenkins
    group: jenkins
  notify:
    - 'Restart Jenkins'

- name: Dynamically create 'build_staging_site' job config with staging web server IP list
  sudo: yes
  template:
    src: "var/lib/jenkins/jobs/build_staging_site/config.xml.j2"
    dest: "/var/lib/jenkins/jobs/build_staging_site/config.xml"
  notify:
    - 'Restart Jenkins'

- name: Copy motd file
- copy: src=/developer.rackspace.com/deploy/roles/jenkins_masters/files/etc/motd dest=/etc/motd owner=jenkins

- name: Setup correct ownerships and permissions
  sudo: yes
  file:
    path: /var/lib/jenkins/
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins
  notify:
    - 'Restart Jenkins'
