---
- name: Create Jenkins users, jobs and other DRG-specific configuration
  sudo: yes
  copy:
    src: var/lib/jenkins/
    dest: /var/lib/jenkins/
  notify:
    - 'Restart Jenkins'

- name: Dynamically set Jenkins IP address in Jenkins config file
  sudo: yes
  template:
    src: var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
  notify:
    - 'Restart Jenkins'

- name: Create directory for 'build_site' job
  sudo: yes
  file:
    path: "/var/lib/jenkins/jobs/build_site"
    state: directory
    owner: jenkins
    group: jenkins
  notify:
    - 'Restart Jenkins'

- name: Dynamically create 'build_site' job config with developer.rackspace.com web server IP list
  sudo: yes
  template:
    src: "var/lib/jenkins/jobs/build_site/config.xml.j2"
    dest: "/var/lib/jenkins/jobs/build_site/config.xml"
  notify:
    - 'Restart Jenkins'

- name: Setup correct ownerships and permissions
  sudo: yes
  file:
    path: /var/lib/jenkins/
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins
  notify:
    - 'Restart Jenkins'
